apiVersion: v2
name: dragonfly
description: Dragonfly is an intelligent P2P based image and file distribution system
icon: https://raw.githubusercontent.com/dragonflyoss/Dragonfly2/main/docs/en/images/logo/dragonfly.svg
type: application
version: "0.1.0"
appVersion: "0.1.0"
keywords:
- dragonfly
- d7y
- P2P
- image

home: https://d7y.io/

sources:
- https://github.com/dragonflyoss/Dragonfly2

annotations:
  artifacthub.io/changes: |
    - Upgrade to the latest template
    - Add README.md
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/dragonflyoss/helm-charts
    - name: Source
      url: https://github.com/dragonflyoss/Dragonfly2
  artifacthub.io/images: |
    - name: dragonflyoss/manager
      image: dragonflyoss/manager:v0.1.0
    - name: dragonflyoss/cdn
      image: dragonflyoss/cdn:v0.1.0
    - name: dragonflyoss/dfdaemon
      image: dragonflyoss/dfdaemon:v0.1.0
    - name: dragonflyoss/scheduler
      image: dragonflyoss/scheduler:v0.1.0

dependencies:
- name: mysql
  version: "8.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mysql.enable
- name: redis-cluster
  version: "5.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enable
