{{- if .Values.installation.jaeger }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-account
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one
  namespace: {{ template "dragonfly.namespace" . }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: ui-configuration
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one-ui-configuration
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-ui-configuration
  namespace: {{ template "dragonfly.namespace" . }}
data:
  ui: |-
    {
      "menu": [
        {
          "items": [
            {
              "label": "Documentation",
              "url": "https://www.jaegertracing.io/docs/1.23"
            }
          ],
          "label": "About"
        }
      ]
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: sampling-configuration
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one-sampling-configuration
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-sampling-configuration
  namespace: {{ template "dragonfly.namespace" . }}
data:
  sampling: |-
    {
      "default_strategy": {
        "param": 1,
        "type": "probabilistic"
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one-collector
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-collector-headless
  namespace: {{ template "dragonfly.namespace" . }}
spec:
  clusterIP: None
  ports:
  - name: http-zipkin
    port: 9411
    targetPort: 0
  - name: http-grpc
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - name: http-c-binary-trft
    port: 14268
    targetPort: 0
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one-collector
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-collector
  namespace: {{ template "dragonfly.namespace" . }}
spec:
  ports:
  - name: http-zipkin
    port: 9411
    targetPort: 0
  - name: http-grpc
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - name: http-c-binary-trft
    port: 14268
    targetPort: 0
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-query
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one-query
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-query
  namespace: {{ template "dragonfly.namespace" . }}
spec:
  ports:
  - name: http-query
    port: 16686
    targetPort: 16686
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: service-agent
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one-agent
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one-agent
  namespace: {{ template "dragonfly.namespace" . }}
spec:
  clusterIP: None
  ports:
  - name: zk-compact-trft
    port: 5775
    protocol: UDP
    targetPort: 0
  - name: config-rest
    port: 5778
    targetPort: 0
  - name: jg-compact-trft
    port: 6831
    protocol: UDP
    targetPort: 0
  - name: jg-binary-trft
    port: 6832
    protocol: UDP
    targetPort: 0
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
    app.kubernetes.io/name: jaeger-all-in-one
    app.kubernetes.io/part-of: jaeger
  name: jaeger-all-in-one
  namespace: {{ template "dragonfly.namespace" . }}
spec:
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: jaeger-all-in-one
      app.kubernetes.io/name: jaeger-all-in-one
      app.kubernetes.io/part-of: jaeger
  strategy: {}
  template:
    metadata:
      labels:
        app: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: jaeger-all-in-one
        app.kubernetes.io/name: jaeger-all-in-one
        app.kubernetes.io/part-of: jaeger
    spec:
      containers:
      - args:
        - --query.ui-config=/etc/config/ui.json
        - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
        env:
        - name: SPAN_STORAGE_TYPE
          value: memory
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: jaegertracing/all-in-one:1.23.0
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 5
          periodSeconds: 15
        name: jaeger
        ports:
        - containerPort: 5775
          name: zk-compact-trft
          protocol: UDP
        - containerPort: 5778
          name: config-rest
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP
        - containerPort: 6832
          name: jg-binary-trft
          protocol: UDP
        - containerPort: 9411
          name: zipkin
        - containerPort: 14267
          name: c-tchan-trft
        - containerPort: 14268
          name: c-binary-trft
        - containerPort: 16686
          name: query
        - containerPort: 14269
          name: admin-http
        - containerPort: 14250
          name: grpc
        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: jaeger-all-in-one-ui-configuration-volume
          readOnly: true
        - mountPath: /etc/jaeger/sampling
          name: jaeger-all-in-one-sampling-configuration-volume
          readOnly: true
      serviceAccountName: jaeger-all-in-one
      volumes:
      - configMap:
          items:
          - key: ui
            path: ui.json
          name: jaeger-all-in-one-ui-configuration
        name: jaeger-all-in-one-ui-configuration-volume
      - configMap:
          items:
          - key: sampling
            path: sampling.json
          name: jaeger-all-in-one-sampling-configuration
        name: jaeger-all-in-one-sampling-configuration-volume
{{- end }}
