apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "dragonfly.cdn.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.cdn.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "dragonfly.cdn.fullname" . }}
  namespace: {{ template "dragonfly.namespace" . }}
  {{- if .Values.cdn.statefulsetAnnotations }}
  annotations:
{{ toYaml .Values.cdn.statefulsetAnnotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.cdn.replicas }}
  selector:
    matchLabels:
      app: {{ template "dragonfly.cdn.fullname" . }}
      component: "{{ .Values.cdn.name }}"
      release: {{ .Release.Name }}
  serviceName: cdn
  template:
    metadata:
      labels:
        app: {{ template "dragonfly.cdn.fullname" . }}
        component: "{{ .Values.cdn.name }}"
        release: {{ .Release.Name }}
        {{- if .Values.cdn.podLabels }}
{{ toYaml .Values.cdn.podLabels | indent 8 }}
        {{- end }}
      {{- if .Values.cdn.podAnnotations }}
      annotations:
{{ toYaml .Values.cdn.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{template "dragonfly.cdn.fullname" . }}
      {{- if .Values.cdn.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.cdn.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.cdn.tolerations }}
      tolerations:
{{ toYaml .Values.cdn.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.cdn.affinity }}
      affinity:
{{ toYaml .Values.cdn.affinity | indent 8 }}
      {{- end }}
      {{- if quote .Values.cdn.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.cdn.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.cdn.priorityClassName) }}
      priorityClassName: {{ .Values.cdn.priorityClassName }}
      {{- end }}
      initContainers:
      - name: wait-for-manager
        image: toschneck/wait-for-it:latest
        args:
          - "-t"
          - "0"
          - {{ template "dragonfly.manager.fullname" . }}:{{ .Values.manager.restPort }}
      containers:
      - name: cdn
        image: "{{ .Values.cdn.image }}:{{ .Values.cdn.tag }}"
        imagePullPolicy: {{ .Values.cdn.pullPolicy | quote }}
        resources:
{{ toYaml .Values.cdn.resources | indent 12 }}
        ports:
        - containerPort: {{ .Values.cdn.containerPort }}
          protocol: TCP
        - containerPort: {{ .Values.cdn.nginxContiainerPort }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/etc/dragonfly"
        - name: nginx-config
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
      volumes:
      - name: config
        configMap:
          name: {{ template "dragonfly.cdn.fullname" . }}
          items:
          - key: cdn.yaml
            path: cdn.yaml
      - name: nginx-config
        configMap:
          name: {{ template "dragonfly.cdn.fullname" . }}
