{{- if .Values.scheduler.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.scheduler.fullname" . }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  scheduler.yaml: |-
    deubug: {{ .Values.scheduler.config.debug }}
    server:
      port: {{ .Values.scheduler.containerPort }}
    worker:
{{ toYaml .Values.scheduler.config.worker | indent 6 }}
    dynconfig:
{{ toYaml .Values.scheduler.config.dynconfig | indent 6 }}
    manager:
      {{- if .Values.externalManager.enable }}
      addr: {{ .Values.externalManager.host }}:{{ .Values.externalManager.grpcPort }}
      {{- else }}
      addr: {{ template "dragonfly.manager.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.manager.grpcPort }}
      {{- end }}
      schedulerClusterID: {{ .Values.scheduler.config.manager.schedulerClusterID }}
      keepAlive:
{{ toYaml .Values.scheduler.config.manager.keepAlive | indent 8 }}
    job:
      redis:
        password: {{ .Values.redis.password }}
        {{- if and (not .Values.externalManager.enable) .Values.redis.enable }}
        host: {{ .Release.Name }}-{{ default "redis" .Values.redis.fullname }}-master.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
        {{- else }}
        host: {{ .Values.redis.host }}
        {{- end }}
        port: {{ .Values.redis.service.port }}
{{- end }}
